### ISSUE TITLE
Support multiple spaces after tag name

### ISSUE THREAD

**Issue by waldyrious** [heyitsdoodler/hbml#10]
According to the parser at https://aydenh.ca/hbml/,

|HBML|HTML|
|-|-|
|`b { "foo" }`|`<b>foo</b>`|
|`b  { "foo" }`|`<b></b><div>foo</div>`|

I'd expect the two inputs to be equivalent.

**Comment by heyitsdoodler** [comment]
I'll check this against the latest version, the parser on the site is out of date.

**Comment by RosiePuddles** [comment]
as per current commit, this isn't an issue and works as expected
