### ISSUE TITLE
Inline elements should be nestable inline

### ISSUE THREAD

**Issue by waldyrious** [heyitsdoodler/hbml#11]
IMHO `b > i > "foo"` should result in 

```html
<b><i>foo</i></b>
```

rather than 

```html
<b>
<i>foo</i>
</b>
```

In other words, the same way that the `i` can detect that its contents are inline, that should be recursively detectable by the `b` as well.

**Comment by heyitsdoodler** [comment]
The two outputs you showed are equivalent, the hbml parser does not prettyify the html it outputs.

Aydenh.ca on the other hand has a primitive html prettifier that runs on the output.

**Comment by waldyrious** [comment]
Fair enough, but I do think it could be worth explicitly declaring the strategy for printing the output. In other words, IMHO there should be a canonical output, following clear and consistent rules.

For example, it could be a pure AST mode, with all tags fully expanded, without optimizations like the "foo" being surrounded by the `<i>` in the same line; or the strategy could be of a pragmatic format with  heuristics like always collapsing chains of nested elements with a single child all the way to the leaf, etc. Currently it seems to be whatever the implementation produces, which I don't think is ideal.
