### ISSUE TITLE
Simplified syntax for literal blocks

### ISSUE THREAD

**Issue by rantvm** [heyitsdoodler/hbml#2]
Instead of allowing double-quoted strings to contain newlines, a "literal block" element should be defined for script/style tags (currently denoted as `{ " ...contents... " }`). These blocks should be opened with a special token, e.g. `{{` or `={`. Semantically, this special opening brace indicates that the contents are to be appended verbatim to the `innerText` of the element.

**Comment by Hjagu09** [comment]
square brackets could maybe be used for that purpos

**Comment by rantvm** [comment]
> This is an interesting idea but because style and script tags both contain braces this seems like it would necessitate escaping all braces in the literal
> 
> Do you have anything to add to this suggestion that would resolve that

Good point, however similar consideration already exists for the double-quoted contents. One option is to require that the braces in script and style tags are balanced as unbalanced tags would be a syntax error in JS/CSS anyway. The other option is to use a closing token that is nonsensical in the embedded languages, e.g. `=}`. One example I am familiar with is nearley with its `{%` and `%}`, used to embed JS in a parser description language.

**Comment by heyitsdoodler** [comment]
This could work.

I've also made some changes to the syntax to support use of double quotes, single quotes, and back tick quotes to define string literals.

Combined with a new syntax using '>' you're are now able to form script and style tags like this:

script > `

...contents...

`

**Comment by heyitsdoodler** [comment]
Understandable, perhaps newlines could be stripped out of double quote and single quote strings but left in back tick strings
