### ISSUE TITLE
Add // as a comment identifier

### ISSUE THREAD

**Issue by DanWlker** [heyitsdoodler/hbml#5]
Currently // does not register as a comment, possible to add it as a comment identifier?

![image](https://user-images.githubusercontent.com/60170554/206871039-c2455dab-e08b-4c24-9db0-e959e26376a4.png)

**Comment by heyitsdoodler** [comment]
This would make sense, I'll make the change

**Comment by heyitsdoodler** [comment]
This change will be implemented along with a major rewrite that is currently being conducted on another fork
