### ISSUE TITLE
Feature request: HTML to HBML converter

### ISSUE THREAD

**Issue by waldyrious** [heyitsdoodler/hbml#6]
Basically the reverse of the HBML parser in https://aydenh.ca/hbml/. I think it would be nice if one could simply paste some HTML code and have it transformed to HBML — it would definitely help conveying the appeal of this project. In a sense, it would have a role similar to the [HTML vs HBML examples](https://github.com/heyitsdoodler/hbml#html-vs-hbml-examples) section of the README, but it would be adaptable to the reader's own needs/preferences.

**Comment by heyitsdoodler** [comment]
Good idea and entirely possible.

I'm currently in the process of finalizing features and improving the syntax with someone more skilled in parsing than I am, this is certainly something we can do once we've concluded this work.

**Comment by heyitsdoodler** [comment]
The website is now much more capable with syntax highlighting and the capability to convert HTML back into HBML.

**Comment by waldyrious** [comment]
> and the capability to convert HTML back into HBML.

Hmm, I'm not seeing that at https://aydenh.ca/hbml/ 🤔 How does one access that functionality?

**Comment by heyitsdoodler** [comment]
Clicking view source will grant you access to the HTML, ensure you've cleared your cache so that you are seeing the current version of the site

**Comment by waldyrious** [comment]
Oh! That's sneaky :) I would probably suggest a different label, since "View source" doesn't suggest that the HTML code is editable and that changing it will affect the HBML side. How about something like "Show HTML editor"?

Also, I think it would be more useful to show the code view first. Any reasonably complex markup language can output to HTML, that's not really a selling point of HBML — the real differentiator is how the code looks compared to HTML, so IMHO it would make sense to highlight that up-front.
