### ISSUE TITLE
namespaces

### ISSUE THREAD

**Issue by RosiePuddles** [heyitsdoodler/hbml#8]
When importing a macro with a namespace that uses another namespace, the internal macro reference is not converted to use the new namespace prefixed macro
```hbml
// file1.hbml
--test2 > "words"
--test > :test2

// file2.hbml
@import file1 f1
:f1:test
```
This raises an error and should

**Comment by heyitsdoodler** [comment]
Namespaces are being applied to built in macros such as :consume-all
